### ISSUE TITLE
Material Theme - ComboBox and TextBox misaligned 

### ISSUE THREAD

**Issue by blemaire** [telerik/kendo-themes#556]
## I'm submitting a...
* Bug report

## Current behavior
A Combox box with a floating label is not aligned with a TextBox with a floating label:

![image](https://user-images.githubusercontent.com/7140322/51258901-52c11b80-19ab-11e9-8ec5-c94ed163c48e.png)

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-p9jmsj

## Environment
Product:
* Kendo Ui for Angular

Package versions:
kendo-theme-material@2.2.0/

Browser:
- Chrome (desktop) version 71.0.3578.98

System:
- Platform:  Mac

**Comment by elena-gancheva** [comment]
The fix is available in the [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the themе.

**Comment by joneff** [comment]
fixed by #584

**Comment by blemaire** [comment]
I just tested the latest version of this theme but the issue is still present:

https://stackblitz.com/edit/angular-tkenjg?file=src%2Fapp%2Fapp.component.html
