### ISSUE TITLE
[Grid] kendoGridNoRecordsTemplate no longer full width

### ISSUE THREAD

**Issue by pabloxn** [telerik/kendo-themes#781]
The kendoGridNoRecordsTemplate no longer stretches to the full width of the grid. It now is limited to the first column. 

**Expected behavior**
I would expect it to stretch across the whole grid as it did before

**Screenshots**
![Screenshot 2019-06-13 at 11 45 21](https://user-images.githubusercontent.com/18709271/59426754-d81cf080-8dd0-11e9-92cb-aadaf460b0a0.png)

**Browser**
 - OS: Mac Mojave
 - Browser: Chrome
 - Version 74

**Comment by joneff** [comment]
@TeyaVes it appears that it's an side effect of #746

**Comment by joneff** [comment]
@pabloxn the fix is merged in develop branch and will shortly be available in the dev channel. You can obtain it and verify.

**Comment by acohenOT** [comment]
This is still broken in the 2019-06-21 service update. When is this fix expected to be released?

**Comment by joneff** [comment]
@acohenOT can you provide an example in which the grid is broken?

Note on dev channel themes: you must install them with `@dev` e.g. `npm install --save-dev @progress/kendo-theme-default@dev` or add `@dev` in the package.json.

Finally, the fix will be available with v4 of the themes as opposed to v3.x, since we introduced changes related to dart-sass compilation.

**Comment by lennerd** [comment]
Just installed `@progress/kendo-theme-default` with `dev` channel. Issue seems to be fixed. Thanks for the quick response.

Is there a way to get notified when this landed in `latest`?

**Comment by acohenOT** [comment]
@joneff here's an example [https://stackblitz.com/edit/angular-z9nu9d-fu8jwh?file=app/app.component.ts](https://stackblitz.com/edit/angular-z9nu9d-fu8jwh?file=app/app.component.ts)

I can't use a dev package in a production app. Can you tell me when v4 will be released in `latest` with this fix?
